server:
  port: 8084
  #应用名称（nacos会将改名称当做服务名称）
spring:
  application:
    name: cloud-provider-service
  cloud:
    nacos:
      server-addr: 47.100.65.75:80
      discovery:
        username: nacos
        password: nacos
        namespace: public
        #ephemeral: false