server:
  port: 8091
  #应用名称（nacos会将改名称当做服务名称）
spring:
  application:
    name: cloud-consumer-openfeign-service
  cloud:
    nacos:
      server-addr: 47.100.65.75:80
      discovery:
        username: nacos
        password: nacos
        namespace: public #相同特征的服务进行归类分组管理
        # ephemeral: false #永久实例，宕机实例也不会删除
        # service: 默认是${spring.application.name}
        # group: 更细的分组
        # weight: 负载均衡权重 权重越高分配的流量越大
        # metadata: version=1  元数据拓展
cloud-provider-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

Ribbon:
  eager-load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置服务使用饥饿加载，多个使用逗号分隔
    clients: cloud-provider-service

#Springboot默认的日志级别是info，feign的debug日志就不会输入
logging:
  level:
    com.feng.cloud.feign: debug

#feign日志局部配置
feign:
  client:
    config:
      cloud-provider-service:
        logger-level: full
      # 服务之间连接超时时间 默认是2s
        connectTimeout: 5000
      # 请求处理超时回见，默认是5s
        readTimeout: 10000
      # 拦截器
        request-interceptors: com.feng.cloud.interceptor.FeignRequestInterceptor
