server:
  port: 8084
  #应用名称（nacos会将改名称当做服务名称）
spring:
  application:
    name: cloud2-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false